# Alembic configuration file

[alembic]
# path to migration scripts
sqlalchemy.url =
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field when generating a new migration
# filename.
# set to 0 to disable, which results in new files getting the full datetime
# string.
# filename_character_set = utf-8

# Use the following variable to control the character mapping produced by the
# "slug" feature.  In some cases you may want the "slug" to be entirely uppercase
# (converted with str.upper()).  In other cases, the segment at the beginning, (u_,
# rev, etc.) can be desired to be lowercase.  Decide on one or the other of
# these name styles for consistency.
#
# use_rev_id = False

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
