"""initial_schema

Revision ID: 8f740a3a2bda
Revises: 
Create Date: 2026-08-19 15:29:18.324290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f740a3a2bda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_status', 'conversations', ['status'], unique=False)
    op.create_index('idx_conversation_tg_id', 'conversations', ['tg_id'], unique=False)
    op.create_index('idx_conversation_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_tg_id'), 'conversations', ['tg_id'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('knowledge_base_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_version_effective_date', 'knowledge_base_versions', ['effective_date'], unique=False)
    op.create_index('idx_kb_version_kb_id', 'knowledge_base_versions', ['kb_id'], unique=False)
    op.create_index('idx_kb_version_owner', 'knowledge_base_versions', ['owner'], unique=False)
    op.create_index('idx_kb_version_review_date', 'knowledge_base_versions', ['review_date'], unique=False)
    op.create_index('idx_kb_version_status', 'knowledge_base_versions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_created_at'), 'knowledge_base_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_effective_date'), 'knowledge_base_versions', ['effective_date'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_kb_id'), 'knowledge_base_versions', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_owner'), 'knowledge_base_versions', ['owner'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_review_date'), 'knowledge_base_versions', ['review_date'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_status'), 'knowledge_base_versions', ['status'], unique=False)
    op.create_table('referral_ownership_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referral_mapping_is_active', 'referral_ownership_mappings', ['is_active'], unique=False)
    op.create_index('idx_referral_mapping_promo_code', 'referral_ownership_mappings', ['promo_code'], unique=False)
    op.create_index('idx_referral_mapping_user_id', 'referral_ownership_mappings', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_ownership_mappings_created_at'), 'referral_ownership_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_ownership_mappings_is_active'), 'referral_ownership_mappings', ['is_active'], unique=False)
    op.create_index(op.f('ix_referral_ownership_mappings_promo_code'), 'referral_ownership_mappings', ['promo_code'], unique=True)
    op.create_index(op.f('ix_referral_ownership_mappings_user_id'), 'referral_ownership_mappings', ['user_id'], unique=True)
    op.create_table('review_promo_code_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_promo_code', 'review_promo_code_usages', ['promo_code'], unique=False)
    op.create_index('idx_review_promo_is_active', 'review_promo_code_usages', ['is_active'], unique=False)
    op.create_index('idx_review_promo_review_id', 'review_promo_code_usages', ['review_id'], unique=False)
    op.create_index('idx_review_promo_user_id', 'review_promo_code_usages', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_promo_code_usages_created_at'), 'review_promo_code_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_promo_code_usages_is_active'), 'review_promo_code_usages', ['is_active'], unique=False)
    op.create_index(op.f('ix_review_promo_code_usages_promo_code'), 'review_promo_code_usages', ['promo_code'], unique=True)
    op.create_index(op.f('ix_review_promo_code_usages_review_id'), 'review_promo_code_usages', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_promo_code_usages_user_id'), 'review_promo_code_usages', ['user_id'], unique=False)
    op.create_table('handoff_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('investigation_summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_handoff_ticket_assigned_to', 'handoff_tickets', ['assigned_to'], unique=False)
    op.create_index('idx_handoff_ticket_conversation_id', 'handoff_tickets', ['conversation_id'], unique=False)
    op.create_index('idx_handoff_ticket_status', 'handoff_tickets', ['status'], unique=False)
    op.create_index('idx_handoff_ticket_trigger_type', 'handoff_tickets', ['trigger_type'], unique=False)
    op.create_index('idx_handoff_ticket_user_id', 'handoff_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_assigned_to'), 'handoff_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_conversation_id'), 'handoff_tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_created_at'), 'handoff_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_status'), 'handoff_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_trigger_type'), 'handoff_tickets', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_user_id'), 'handoff_tickets', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_ticket_conversation_id', 'support_tickets', ['conversation_id'], unique=False)
    op.create_index('idx_support_ticket_flow_type', 'support_tickets', ['flow_type'], unique=False)
    op.create_index('idx_support_ticket_state', 'support_tickets', ['state'], unique=False)
    op.create_index(op.f('ix_support_tickets_conversation_id'), 'support_tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_table('collected_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handoff_ticket_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handoff_ticket_id'], ['handoff_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collected_fact_source', 'collected_facts', ['source'], unique=False)
    op.create_index('idx_collected_fact_ticket_id', 'collected_facts', ['handoff_ticket_id'], unique=False)
    op.create_index('idx_collected_fact_type', 'collected_facts', ['fact_type'], unique=False)
    op.create_index(op.f('ix_collected_facts_created_at'), 'collected_facts', ['created_at'], unique=False)
    op.create_index(op.f('ix_collected_facts_handoff_ticket_id'), 'collected_facts', ['handoff_ticket_id'], unique=False)
    op.create_table('support_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('support_ticket_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('frozen_params', sa.JSON(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=50), nullable=False),
    sa.Column('approval_actor_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_action_idempotency_key', 'support_actions', ['idempotency_key'], unique=False)
    op.create_index('idx_support_action_status', 'support_actions', ['status'], unique=False)
    op.create_index('idx_support_action_ticket_id', 'support_actions', ['support_ticket_id'], unique=False)
    op.create_index('idx_support_action_type', 'support_actions', ['type'], unique=False)
    op.create_index(op.f('ix_support_actions_created_at'), 'support_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_actions_idempotency_key'), 'support_actions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_support_actions_support_ticket_id'), 'support_actions', ['support_ticket_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('support_action_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['support_action_id'], ['support_actions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_log_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_log_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_support_action_id'), 'audit_logs', ['support_action_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_support_action_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('idx_audit_log_target_id', table_name='audit_logs')
    op.drop_index('idx_audit_log_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_log_actor_id', table_name='audit_logs')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_support_actions_support_ticket_id'), table_name='support_actions')
    op.drop_index(op.f('ix_support_actions_idempotency_key'), table_name='support_actions')
    op.drop_index(op.f('ix_support_actions_created_at'), table_name='support_actions')
    op.drop_index('idx_support_action_type', table_name='support_actions')
    op.drop_index('idx_support_action_ticket_id', table_name='support_actions')
    op.drop_index('idx_support_action_status', table_name='support_actions')
    op.drop_index('idx_support_action_idempotency_key', table_name='support_actions')
    op.drop_table('support_actions')
    op.drop_index(op.f('ix_collected_facts_handoff_ticket_id'), table_name='collected_facts')
    op.drop_index(op.f('ix_collected_facts_created_at'), table_name='collected_facts')
    op.drop_index('idx_collected_fact_type', table_name='collected_facts')
    op.drop_index('idx_collected_fact_ticket_id', table_name='collected_facts')
    op.drop_index('idx_collected_fact_source', table_name='collected_facts')
    op.drop_table('collected_facts')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_conversation_id'), table_name='support_tickets')
    op.drop_index('idx_support_ticket_state', table_name='support_tickets')
    op.drop_index('idx_support_ticket_flow_type', table_name='support_tickets')
    op.drop_index('idx_support_ticket_conversation_id', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_handoff_tickets_user_id'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_trigger_type'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_status'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_created_at'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_conversation_id'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_assigned_to'), table_name='handoff_tickets')
    op.drop_index('idx_handoff_ticket_user_id', table_name='handoff_tickets')
    op.drop_index('idx_handoff_ticket_trigger_type', table_name='handoff_tickets')
    op.drop_index('idx_handoff_ticket_status', table_name='handoff_tickets')
    op.drop_index('idx_handoff_ticket_conversation_id', table_name='handoff_tickets')
    op.drop_index('idx_handoff_ticket_assigned_to', table_name='handoff_tickets')
    op.drop_table('handoff_tickets')
    op.drop_index(op.f('ix_review_promo_code_usages_user_id'), table_name='review_promo_code_usages')
    op.drop_index(op.f('ix_review_promo_code_usages_review_id'), table_name='review_promo_code_usages')
    op.drop_index(op.f('ix_review_promo_code_usages_promo_code'), table_name='review_promo_code_usages')
    op.drop_index(op.f('ix_review_promo_code_usages_is_active'), table_name='review_promo_code_usages')
    op.drop_index(op.f('ix_review_promo_code_usages_created_at'), table_name='review_promo_code_usages')
    op.drop_index('idx_review_promo_user_id', table_name='review_promo_code_usages')
    op.drop_index('idx_review_promo_review_id', table_name='review_promo_code_usages')
    op.drop_index('idx_review_promo_is_active', table_name='review_promo_code_usages')
    op.drop_index('idx_review_promo_code', table_name='review_promo_code_usages')
    op.drop_table('review_promo_code_usages')
    op.drop_index(op.f('ix_referral_ownership_mappings_user_id'), table_name='referral_ownership_mappings')
    op.drop_index(op.f('ix_referral_ownership_mappings_promo_code'), table_name='referral_ownership_mappings')
    op.drop_index(op.f('ix_referral_ownership_mappings_is_active'), table_name='referral_ownership_mappings')
    op.drop_index(op.f('ix_referral_ownership_mappings_created_at'), table_name='referral_ownership_mappings')
    op.drop_index('idx_referral_mapping_user_id', table_name='referral_ownership_mappings')
    op.drop_index('idx_referral_mapping_promo_code', table_name='referral_ownership_mappings')
    op.drop_index('idx_referral_mapping_is_active', table_name='referral_ownership_mappings')
    op.drop_table('referral_ownership_mappings')
    op.drop_index(op.f('ix_knowledge_base_versions_status'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_review_date'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_owner'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_kb_id'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_effective_date'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_created_at'), table_name='knowledge_base_versions')
    op.drop_index('idx_kb_version_status', table_name='knowledge_base_versions')
    op.drop_index('idx_kb_version_review_date', table_name='knowledge_base_versions')
    op.drop_index('idx_kb_version_owner', table_name='knowledge_base_versions')
    op.drop_index('idx_kb_version_kb_id', table_name='knowledge_base_versions')
    op.drop_index('idx_kb_version_effective_date', table_name='knowledge_base_versions')
    op.drop_table('knowledge_base_versions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_tg_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('idx_conversation_user_id', table_name='conversations')
    op.drop_index('idx_conversation_tg_id', table_name='conversations')
    op.drop_index('idx_conversation_status', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
